### ISSUE TITLE
Strange Error regarding import_map.json in the new v1.53.4

### ISSUE THREAD

**Issue by danielxpander** [supabase/edge-runtime#363] opened 2024-06-12 15:12 UTC
Here's some deployment message I get when it's failing:
Status: Downloaded newer image for ghcr.io/supabase/edge-runtime:v1.53.4
Stopping containers...
failed to create volume: Error response from daemon: create supabase/functions/import_map.json: "supabase/functions/import_map.json" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path

I didn't change the import map json
Thank you

**Comment by laktek** [comment] 2024-06-12 15:40
@danielxpander I guess you're running Edge Runtime via Supabase CLI? What's the CLI version?

**Comment by danielxpander** [comment] 2024-06-13 06:10
Yes, 
supabase/setup-cli@v1
and it's being run from github actions

**Comment by laktek** [comment] 2024-06-13 19:55
@danielxpander This issue is fixed in CLI https://github.com/supabase/cli/pull/2420. A stable release would be made in the next 24-48 hours.

**Comment by sweatybridge** [comment] 2024-06-14 06:21
Stable release is out. Feel free to close it if the fix is working for you.

**Comment by jad-eljerdy** [comment] 2024-06-14 22:48
Hey,

Getting a similar error 

`failed to create volume: Error response from daemon: create supabase_edge_runtime_<no value>: "supabase_edge_runtime_<no value>" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path`

I'm using CLI version **1.176.10**

Might be a docker issue ? Couldn't find a reference to the issue anywhere. Let me know if I should create a separate issue for this.

**Comment by sweatybridge** [comment] 2024-06-15 03:14
@jad-eljerdy is the error from functions serve or supabase start?

Could you also show me the value of project_id field in supabase/config.toml?

**Comment by danielxpander** [comment] 2024-06-16 07:01
> @jad-eljerdy is the error from functions serve or supabase start?
> 
> Could you also show me the value of project_id field in supabase/config.toml?

Supabase start

**Comment by sweatybridge** [comment] 2024-06-16 10:42
@danielxpander are you still running into this on latest cli? Your original problem is different from that reported by @jad-eljerdy and should be already resolved in latest release.

**Comment by nyannyacha** [comment] 2024-07-30 21:46
We are closing this issue for housekeeping.

This issue does not appear to be reproducible in the current version. Please feel free to reopen this issue if you have the same problem again.

**Closed by nyannyacha** 2024-07-30 21:46 UTC
Labels: bug
