### ISSUE TITLE
[Supabase Edge Functions] Can't use Websockets in Edge Functions on Supabase Hosting.

### ISSUE THREAD

**Issue by Lan-Hekary** [supabase/edge-runtime#393] opened 2024-04-16 15:55 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am trying to connect to Supabase Edge Function via WebSocket.
I managed to connect to the Edge Function locally and even when I expose the local instance of the Function to the internet I can connect to it from outside.
But as soon as I Deploy the function to a Supabase Project The WebSocket Connection fails.
I am not sure if it's a Bug or it's not supported.

## To Reproduce

1. Create a Supabase function using the CLI: `Supabase functions new ws`

2. Use This code is based on this [article](https://deno.com/blog/deploy-streams) from Deno:
```
Deno.serve((req) => {
  console.log("got :", req)
  const upgrade = req.headers.get("upgrade") || ""
  if (upgrade.toLowerCase() != "websocket") {
    return new Response("request isn't trying to upgrade to websocket.")
  }
  const { socket, response } = Deno.upgradeWebSocket(req)
  socket.onopen = () => console.log("socket opened")
  socket.onmessage = (e) => {
    console.log("socket message:", e.data)
    socket.send(new Date().toString())
  }
  socket.onerror = (e) => console.log("socket errored:", e.message, e)
  socket.onclose = (e) => console.log("socket closed clean:", e.wasClean)
  return response
})
```
3. Up to this Step if you started the function using `supabase functions serve --no-verify-jwt` and opened a WebSocket connection to the local instance of the edge-runtime, it will work just fine. The Bug is in the Next Step.

4. Deploy the Function using CLI: `supabase functions deploy ws --no-verify-jwt`.
5. Try to connect to the function via the Webbrowser or using https://websocketking.com/, it will fail as it can't connect, but in the logs of the function you will findout that the socket opens and immediately errors out then closes with an error message 'Unexpected EOF'

## Expected behavior

It Should work in Supabase Projects as it's working in the local runtime.

## Screenshots
The local CLI instance Working Properly.
![image](https://github.com/supabase/supabase/assets/13420623/e263c1e6-525a-4a2a-91ac-1cbeecdbacfd)

The log in the Dashboard showing the failure.
![image](https://github.com/supabase/supabase/assets/13420623/7356c8ab-6210-42cc-ae16-3e08b933f3f5)

## System information

- OS: Linux Arm64
- Browser: Edge
- Version of supabase-cli: v1.157.2
- Version of Node.js: v18.20.2

## Additional context

My Reference is this Official [Video ](https://www.youtube.com/watch?v=9N66JBRLNYU) which referenced this [article ](https://deno.com/blog/deploy-streams) from Deno.

I Duplicated the Video for the Server-Side-Events, and it works as Expected both locally and on Supabase Projects.
The video talks about WebSockets briefly but does not implement it.

**Comment by encima** [comment] 2024-07-29 11:13
Moving to edge-runtime to help the team track it as a feature request.

**Comment by haschu** [comment] 2024-10-02 11:43
Given the new realtime API from OpenAI that relies on websockets , are there any plans to implement this feature in the foreseeable future?

**Comment by haschu** [comment] 2024-10-19 17:17
Hey, just a friendly reminder :) 

This is labeled as "enhancement" while it's actually a bug, there is even an [example](https://github.com/supabase/edge-runtime/blob/main/examples/ws/index.ts) on how to use websockets in this repo, which results in the same error.

**Comment by nyannyacha** [comment] 2024-10-20 00:43
Hello @haschu 😋

I checked the example you mentioned, but WebSocket seems to be working fine locally.
Can you provide reproducible steps?

Note that currently, this feature is not available in Edge Functions (aka, Supabase Hosted), only self-hosted users deploying the edge runtime on-premise environment can use it.

**Comment by haschu** [comment] 2024-10-21 08:16
@nyannyacha 
Thanks for your reply 🙃
sorry... my bad, I thought it should be working on Supabase hosted as well. Are there any plans for this feature in the near future?

**Comment by BrandiATMuhkuh** [comment] 2024-11-29 07:14
Hi Supabase, 

Hi Supabase. Are there any updates on this front? 
I second @haschu thoughts regarding openAi realtime. That's exactly my use case.

Can you suggest other deno-edge providers which allow the feature? (You've mentioned above it's your provider that causes the issue).

**Comment by nyannyacha** [comment] 2024-12-03 23:42
We are closing this issue as we now support WebSocket in Supabase Edge Functions (hosted environment).
Please see the latest guide.
https://supabase.com/docs/guides/functions/websockets

**Closed by nyannyacha** 2024-12-03 23:42 UTC
Labels: enhancement, category: hosted
