### ISSUE TITLE
Import maps don't take NPM modules

### ISSUE THREAD

**Issue by andreespirela** [supabase/edge-runtime#243] opened 2024-01-10 02:43 UTC
# Bug report
Currently, NPM modules are not supported in import maps. It makes the runtime fail:

**Import map:**
```json
{
  "imports": {
    "iseven": "npm:is-even"
  }
}
```
**Code:**
```
import isEven from "iseven"; 
globalThis.isTenEven = isEven(9);
```
**Panic**
```
thread 'deno_runtime::test::test_eszip_with_source_file' panicked at crates/base/src/deno_runtime.rs:491:30:\ncalled `Result::unwrap()` on an `Err` value: Relative import path \"iseven\" not prefixed with / or ./ or ../ f
```

**Comment by maleksal** [comment] 2024-05-21 18:45
Any updates about this issue ? I'm using self-hosted Supabase and I'm facing the same issue

```
"msg": "InvalidWorkerCreation: worker boot error Relative import path \"express\" not prefixed with / or ./ or ../ from \"file:///home/deno/functions/imap/index.ts\""
```

**Comment by nyannyacha** [comment] 2024-06-25 02:27
I was unable to reproduce this behavior on the main branch.
Closing the issue.

cc @andreespirela @maleksal

**Closed by nyannyacha** 2024-06-25 02:27 UTC
Labels: bug
