### ISSUE TITLE
Neither old (experimental) decorators nor new (stage 3) decorators work since upgrading to Deno 1.40

### ISSUE THREAD

**Issue by hammerlscs** [supabase/edge-runtime#296] opened 2024-03-22 11:31 UTC
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Neither the old (experimental) decorators nor the new (stage 3) decorators work since upgrading to Deno 1.40:

```
Setting up Edge Functions runtime...
Serving functions on http://localhost:54321/functions/v1/<function-name>

Using supabase-edge-runtime-1.38.0 (compatible with Deno v1.40.3)

serving the request with /home/deno/functions/test

Uncaught SyntaxError: Invalid or unexpected token
    at file:///home/deno/functions/test/index.ts:14:3

An error has occured

InvalidWorkerCreation: worker boot error
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:141:15)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:129:20)
    at async #respond (https://deno.land/std@0.182.0/http/server.ts:220:18) {
  name: "InvalidWorkerCreation"
}
```

The new stage 3 decorators possibly do not work because of: https://github.com/denoland/deno/issues/22419

And the old experimental decorators possibly do not work, because using them requires the configuration

```
{
  "compilerOptions": {
    "experimentalDecorators": true
  }
}
```

(https://deno.com/blog/v1.40#decorators)

## To Reproduce

Create either an edge function with the new stage 3 decorator syntax such as:

```
// deno-lint-ignore no-explicit-any
function trace(fn: any, ctx: ClassMethodDecoratorContext) {
    // deno-lint-ignore no-explicit-any
    return function (...args: unknown[]) {
        console.log("ENTERED", ctx.name);
        const v = fn(...args);
        console.log("EXITED", ctx.name);
        return v;
    };
}

class App {
    @trace
    static start() {
        console.log("Hello World!");
    }
}

Deno.serve(async (req) => {
    const { name } = await req.json()
    const data = {
        message: `Hello ${name}!`,
    }

    App.start();

    return new Response(JSON.stringify(data), { headers: { 'Content-Type': 'application/json' } })
})
```

Or create an edge function with the old experimental decorators such as:

```
function trace(
  // deno-lint-ignore no-explicit-any
  _target: any,
  _methodName: string,
  descriptor: PropertyDescriptor,
) {
  const originalMethod = descriptor.value

  // deno-lint-ignore no-explicit-any
  descriptor.value = function (...args: any[]) {
    console.log('ENTERED')
    const v = originalMethod.call(this, ...args)
    console.log('EXITED')
    return v
  }
  return descriptor
}

class App {
  @trace
  start() {
    console.log('Hello World!')
  }
}

Deno.serve(async (req) => {
  const { name } = await req.json()
  const data = {
    message: `Hello ${name}!`,
  }

  const app = new App()
  app.start()

  return new Response(JSON.stringify(data), { headers: { 'Content-Type': 'application/json' } })
})
```

Then call the edge function:

```
curl -i --location --request POST 'http://localhost:54321/functions/v1/test' \
  --header 'Authorization: Bearer SUPABASE_ANON_KEY' \
  --header 'Content-Type: application/json' \
  --data '{"name":"Is this working"}'
```

## Expected behavior

The decorators work as expected

## System information

Tested with Supabase CLI v1.150.0 and v1.151.0

**Comment by geoffreygarrett** [comment] 2024-03-26 08:27
+1  🙏🏻 

```typescript
import { Service } from "npm:@bluelibs/core";


@Service()
class A {
  init() {
    return true;
  }
}
```

Results in:

```
Setting up Edge Functions runtime...

Serving functions on http://127.0.0.1:54321/functions/v1/<function-name>

Using supabase-edge-runtime-1.38.0 (compatible with Deno v1.40.3)

serving the request with /home/deno/functions/webhook

Uncaught SyntaxError: Invalid or unexpected token
    at file:///home/deno/functions/webhook/index.ts:7:1
```

I've had to rewrite part of an external library because of this.

**Comment by geoffreygarrett** [comment] 2024-03-26 08:31
The core of the issue is that I'd like to use [typedi](https://docs.typestack.community/typedi/v/develop) which requires:

```json
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
```

Is it possible to have this set in the runtimes `deno.json`?

**Comment by hammerlscs** [comment] 2024-03-26 08:40
> The core of the issue is that I'd like to use [typedi](https://docs.typestack.community/typedi/v/develop) which requires:
> 
> ```json
> "emitDecoratorMetadata": true,
> "experimentalDecorators": true,
> ```
> 
> Is it possible to have this set in the runtimes `deno.json`?

With `"experimentalDecorators": true,` only and exclusively the old experimental decorators would work. This would be an improvement, but it would be great, if we could use a `deno.json` config file instead of or in addition to the `import_map.json` file for the edge functions. With this we could control which decorators we want to use.

By then adding `"experimentalDecorators": true,` the old experimental decorators should work again. And as soon as https://github.com/denoland/deno/issues/22419 is fixed and merged, the new stage 3 decorators should work again as well.

**Comment by geoffreygarrett** [comment] 2024-03-26 09:14
> > The core of the issue is that I'd like to use [typedi](https://docs.typestack.community/typedi/v/develop) which requires:
> > ```json
> > "emitDecoratorMetadata": true,
> > "experimentalDecorators": true,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is it possible to have this set in the runtimes `deno.json`?
> 
> With `"experimentalDecorators": true,` only and exclusively the old experimental decorators would work. This would be an improvement, but it would be great, if we could use a `deno.json` config file instead of or in addition to the `import_map.json` file for the edge functions. With this we could control which decorators we want to use.
> 
> By then adding `"experimentalDecorators": true,` the old experimental decorators should work again. And as soon as [denoland/deno#22419](https://github.com/denoland/deno/issues/22419) is fixed and merged, the new stage 3 decorators should work again as well.

It would be preferable to have access to the `deno.json`, but as it stands, they've decided to bundle it with the `supabase-edge-runtime` container, so either we all have it, or none of us do. I'm hoping it's non-impactful to everyone to have the above configuration added.

**Comment by louis-amhild** [comment] 2024-03-26 16:11
I can confirm that decorators no longer work since edge-runtime upgraded to release v1.34.0 (https://github.com/supabase/edge-runtime/pull/262/commits/87f8b69dcd5d6e1c1c8a49b9696f363c8b496b18), which traces back to this PR in Deno, where experimentalDecorators was disabled as default (https://github.com/denoland/deno/pull/22101). 

My upcoming port of TSOA for Deno (https://github.com/louis-amhild/tsoa-deno) stopped working in Supabase and I couldn't understand why (thanks for posting this bug [hammerlscs](https://github.com/hammerlscs)).
 
As announced by the Deno team disabling experimentalDecorators is a very impactful change as "code that was deployed and executed successfully before the change might fail either at build time or runtime if it is redeployed now without any change." (https://deno.com/deploy/changelog#2024-02-22). However they have argued to make the change anyway as developers can just enable experimentalDecorators in the config - which is obviously not possible in Supabase and thous we have this issue.

Waiting for stage 3 decorators to be fixed in Deno (https://github.com/denoland/deno/issues/22419) will only solve the issue partly, as the new decorators in typescript 5 has a different syntax and still lack features ie. “does not allow decorating parameters” for example
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#decorators.

I think [geoffreygarrett](https://github.com/geoffreygarrett) is right that enabling experimentalDecorators as default again is a good solution until Supabase introduces Deno config (some day?) or the stage 3 decorators are fully implemented and adopted in more libraries (in some years). Enabling it would solve the issue and return the previous behaviour as before edge v1.34.0.

Unfortunately I'm not really familiar with the code base so it is difficult for me to make a PR, but maybe someone else could? Maybe you know if it would be easy to enable experimentalDecorators again [andreespirela](https://github.com/andreespirela)?

**Comment by andreespirela** [comment] 2024-03-28 10:00
Sounds reasonable to me

**Comment by geoffreygarrett** [comment] 2024-04-02 10:30
So, could we get it enabled in the runtime container's config for now?

**Closed** 2024-04-14 21:09 UTC
Labels: bug

**Comment by nyannyacha** [comment] 2024-04-14 21:27
I don't know if you are in a hosted or self-hosted environment, but if you are self-hosted, you can now enable the decorator feature (see this [link](https://github.com/supabase/edge-runtime/pull/316)).

If you are using a hosted (Supabase Cloud) environment, it will probably take a while for the decorator feature to be enabled.

**Comment by wave-light** [comment] 2024-05-07 08:05
Can this please be re-opened? The issue is only fixed if you are running Supabase in a self-hosted environment.

**Comment by jsantos-godroplet** [comment] 2024-06-02 10:06
> Can this please be re-opened? The issue is only fixed if you are running Supabase in a self-hosted environment.

Just got this error too. Can we reopen?

supabase-edge-runtime-1.53.3 (Deno v1.40.3)

**Comment by mo2menelzeiny** [comment] 2025-04-23 18:23
Any news on this? are decorators available on Supabase Edge functions or not?

**Comment by nyannyacha** [comment] 2025-04-23 23:54
Hello @mo2menelzeiny,

> Any news on this? are decorators available on Supabase Edge functions or not?

We're sorry for the confusion. We're making a fix after confirming that the decorator isn't enabled.
Applying this fix may take some time, and you may need to redeploy after it is applied.

We will notify you when the fix is applied.

Thank you!

**Comment by iamcxa** [comment] 2025-06-07 12:11
@nyannyacha Hi, do decorators work again on the newest edge function? I integrated https://www.npmjs.com/package/@hono/tsyringe with Deno + hono, and I found that the same code works fine on Deno v1.45.2 but not working on supabase-edge-runtime-1.67.4 (I've set the deno.json with compilerOptions).  So I wonder if this has been fixed, or did I miss anything?

error messages 

```
worker boot error: Uncaught SyntaxError: Invalid or unexpected token

```

**Comment by nyannyacha** [comment] 2025-06-09 08:16
Hello @iamcxa

Assuming you are trying to use experimentalDecorators.
Currently, Supabase Edge Functions only supports tc39, so even if you specify the decorator option in the compilerOptions section in deno.json, it will be ignored.

Once the upcoming Deno 2 update is deployed to Supabase Edge Functions, it will be able to read the decorator option from deno.json, allowing you to use it.
But at this time, there does not appear to be a direct alternative to making it available.

**Comment by iamcxa** [comment] 2025-06-09 10:25
@nyannyacha I see. Thanks for your reply, and super looking forward to Dthe eno 2 update
