### ISSUE TITLE
Background task escapes event loop on first run but works on subsequent runs

### ISSUE THREAD

**Issue by DreamwareDevelopment** [supabase/edge-runtime#460] opened 2024-12-14 09:28 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The following logs occur the first time a background task runs on a local supabase instance.
```
[Info] Starting initial downsync

runtime has escaped from the event loop unexpectedly: event loop error: Interrupted: operation canceled
    at async readableStreamCollectIntoUint8Array (ext:deno_web/06_streams.js:1065:19)
    at async consumeBody (ext:deno_fetch/22_body.js:241:9)
    at async initialDownsync (file:///Users/zander/Documents/Code/goaltime/apps/supabase/supabase/functions/calendar-initial-downsync/index.ts:7:16)
```

The function:
```
import { BeforeUnloadEvent } from "jsr:@supabase/functions-js/edge-runtime.d.ts"

declare const EdgeRuntime: {
  waitUntil: (promise: Promise<any>) => void;
};

async function initialDownsync(req: Request) {
  const body = await req.json()
  console.log('Function request body', JSON.stringify(body, null, 2))
}

addEventListener('beforeunload', (ev: BeforeUnloadEvent) => {
  console.log('Function will be shutdown due to', ev.detail?.reason)
})

// deno-lint-ignore require-await
Deno.serve(async (req: Request) => {
  console.log('Starting initial downsync')
  EdgeRuntime.waitUntil(initialDownsync(req))
  return new Response('ok')
})
```

## Expected behavior

The error shouldn't happen.

## System information

```
deno 2.0.6 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

## Additional context

TLS is enabled on the local instance and I'm calling it via an ngrok tunnel

**Comment by nyannyacha** [comment] 2024-12-16 00:36
Hello @DreamwareDevelopment 

The short answer is that you cannot use `EdgeRuntime.waitUntil` in that way.

You are attempting to create a derived promise (e.g., req.json()) for req via the `initialDownsync` function, but this will not work because, when that promise is processed in the background, the request/response context will expire by the `new Response(‘ok’)` statement.

The `request/response` is a paired context, not a separate context. In other words, if you send a response of `"ok"` to the client, the connection will be closed immediately, so you will not be able to consume the body through `req.json()`.

That is working as intended, so I will close this issue.
If you find a new issue, please create a separate issue.

**Closed by nyannyacha** 2024-12-16 00:36 UTC
Labels: bug

**Comment by DreamwareDevelopment** [comment] 2024-12-16 00:41
Ah, yeah that makes sense that the request context can be reclaimed during the background execution after the edge function promise is resolved. Thanks for the help!
